# Self-hosters, CI servers, etc:
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials: <%= ENV["GOOGLE_CLOUD_KEYFILE_JSON"] %>
  project:     <%= ENV["GCS_PROJECT"] %>
  bucket:      <%= ENV["GCS_BUCKET"] %>
